services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "pnpm install && pnpm run dev"
    depends_on:
      - db-evenset
    env_file:
      - .env

  db-evenset:
    container_name: db-evenset
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer-evenset:
    image: adminer:latest
    container_name: adminer-evenset
    ports:
      - '8080:8080'
    depends_on:
      - db-evenset

volumes:
  data:
  node_modules:
  db-data:
